apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-pod-security-policy
  name: deploy-pod-security-policy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-pod-security-policy
  template:
    metadata:
      labels:
        app: deploy-pod-security-policy
    spec:
      serviceAccountName: deploy-pod-security-policy
      containers:
        - image: andifalk/deploy-pod-security-policy:latest
          name: deploy-pod-security-policy
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "768Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5    
      restartPolicy: Always
