apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-security-context
  name: deploy-security-context
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-security-context
  template:
    metadata:
      labels:
        app: deploy-security-context
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - image: andifalk/deploy-security-context:latest
          name: deploy-security-context
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "768Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5    
      restartPolicy: Always
